version: '3'

services:
  github_scraper:
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    volumes:
      - '.:/usr/src/app'
    environment:
      DB_URL: 'postgres://postgres:password@postgres:5432/api'
    depends_on:
      - postgres
    env_file: .env
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: api
    ports:
      - '5432:5432'
