name: deploy

on:
  push:
    branches:
      - master

jobs:
  caprover:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run Caprover
        uses: AlexxNB/caprover-action@v1
        with:
          server: 'https://captain.api.mattglei.ch'
          password: '${{ secrets.CAPROVER_PASSWORD }}'
          appname: 'github-scraper'
